import { PreviewsItem } from '../../typings/autogen'

export function orderToCsv(order: ReadonlyArray<PreviewsItem>) {
  const headers = 'Previews Code,Quantity,Title,Price,Publisher,Comment'

  const rows = order.map((i: any) => {
    return [
      i.code,
      i.quantity || 1,
      i.title,
      i.price,
      i.publisher,
      i.comment
    ].join(',')
  })
  const output = [
    headers,
    ...rows,
    `,,Total,${order.reduce((acc: number, curr: any) => acc += parseFloat(curr.price), 0).toFixed(2)}`,
    'Generated by Ace My Order'
  ].join('\n')

  return output
}
